Minor version updates and code polishes
neo4j-contrib/spatial pull request #395
Opened 2024-02-28 22:32 UTC by seabamirum

- Upgraded geotools, junit, maven-compiler-plugin and maven-surefire-plugin
- Deleted unused private methods
- Removed unnecessary `else` clauses that were followed by an `if` block with a `return`
- Added missing @Override annotations
- Added  `static` modifier to static methods when suggested by compiler
- In `makeLayerInstance`, replaced deprecated `newInstance` method with `getDeclaredConstructor().newInstance()`

2024-05-28 08:57 UTC, Andy2003 requested changes

2024-05-28 08:57 UTC, Andy2003 commented on src/main/java/org/geotools/data/neo4j/Neo4jSpatialDataStore.java
> +		return source;
Please do not change the indent to tab in this PR (we need to add an additional refomrat PR for this)

2024-05-28 08:57 UTC, Andy2003 commented on src/main/java/org/neo4j/gis/spatial/filter/SearchCQL.java
>      public SearchCQL(Transaction tx, Layer layer, org.geotools.api.filter.Filter filter) {
`tx` can be removed from the constructor as well

2024-05-28 08:57 UTC, Andy2003 commented on src/main/java/org/neo4j/gis/spatial/index/IndexManager.java
>              } catch (Exception e) {
rename `e` to `ignore`

2024-05-28 09:46 UTC, Andy2003 commented on src/main/java/org/geotools/data/neo4j/Neo4jSpatialDataStore.java
> +		return source;
I created a PR for this: https://github.com/neo4j-contrib/spatial/pull/396

2024-05-29 14:37 UTC, Andy2003 commented
@seabamirum Have you already signed the [CLA](https://neo4j.com/developer/cla/)?

2024-05-30 19:46 UTC, seabamirum commented
Yes, I have signed the CLA. I think this branch is all properly synced up now..

2024-05-31 09:10 UTC, Andy2003 requested changes

2024-05-31 09:10 UTC, Andy2003 commented on src/main/java/org/geotools/data/neo4j/DefaultResourceInfo.java
> +}
why did you remove the final line-breaks?

2024-05-31 14:55 UTC, seabamirum commented on src/main/java/org/geotools/data/neo4j/DefaultResourceInfo.java
> +}
Not intended, thanks. Fixed.

2024-06-19 07:59 UTC, Andy2003 commented
@craigtaverner May you take a look at these changes?

2025-02-17 18:25 UTC, Andy2003 approved these changes

2025-02-17 18:35 UTC, Andy2003 requested changes

2025-02-17 18:35 UTC, Andy2003 commented on docs/index.html
Why you checked in this file. The docs get build by and published to the labs project:

 - https://neo4j.com/labs/neo4j-spatial/5/overview/introduction/
- https://neo4j.com/labs/spatial/

2025-04-01 09:07 UTC, Andy2003 commented on docs/index.html
I removed this file from the PR

2025-04-01 09:37 UTC, Andy2003 approved these changes

2025-04-01 09:37 UTC, merged